repos:
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        name: black
        entry: bash -c 'black app --check'
        types: [python]

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      name: flake8
      entry: bash -c 'flake8 app'
      language: system
      types: [python]