repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: black
        entry: bash -c 'black app --check'
        types: [python]

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      name: flake8
      entry: bash -c 'flake8 --max-line-length=88 app'
      language: system
      types: [python]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        entry: bash -c 'isort --profile black app'