version: "3.9"
services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    command: "/code/docker/app.sh"
  
  db:
    image: postgres:15
    container_name: hotels_db
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .dev.env
    ports:
      - 5431:5432
    volumes:
      - database:/var/lib/postgresql/data 

  redis:
    image: redis:7
    container_name: hotels_redis


volumes:
  database:
  


  

