version: "3.9"
services:
  test_web:
    container_name: test_web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONTEXT: "test"
    ports:
      - 8001:8000
    volumes:
      - .:/code
      - /code/.venv
    env_file:
      - .test.env
    depends_on:
      - test_db
      - test_redis
    command: "/code/docker/app.sh"
    tty: true
  
  test_db:
    image: postgres:15
    container_name: test_hotels_db
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .test.env
    ports:
      - 5430:5432
    tmpfs:
      - /var/lib/postgresql/data
    tty: true
    

  test_redis:
    image: redis:7
    container_name: test_hotels_redis
    tmpfs:
      - /data

  test_celery:
    build: 
      context: .
      args:
        CONTEXT: "test"
    container_name: test_hotels_celery
    volumes:
      - .:/code
      - /code/.venv
    command: ["/code/docker/celery.sh", "celery"]
    depends_on:
      - test_redis
    env_file:
      - .test.env
    tty: true


  test_flower:
    build: 
      context: .
      args:
        CONTEXT: "test"
    container_name: test_hotels_flower
    command: ["/code/docker/celery.sh", "flower"]
    env_file:
      - .test.env
    depends_on:
      - test_redis
    ports:
      - 5556:5555
    tty: true