"""removed exprire column from RefreshSessions

Revision ID: 77f5ff776ec4
Revises: cd63b80a8e18
Create Date: 2023-07-21 21:55:21.957885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f5ff776ec4'
down_revision = 'cd63b80a8e18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_sessions', 'expire')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_sessions', sa.Column('expire', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
