"""added unique constraint to user_id RefreshSessions

Revision ID: 747917d67993
Revises: d4c1e707b91a
Create Date: 2023-07-21 03:46:55.788660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747917d67993'
down_revision = 'd4c1e707b91a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'refresh_sessions', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_sessions', type_='unique')
    # ### end Alembic commands ###
