"""added nullable address arg to Hotels

Revision ID: 7c156448b25e
Revises: 5cd5dce283b3
Create Date: 2023-07-17 01:47:30.460312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c156448b25e'
down_revision = '5cd5dce283b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
