"""removed unique constraint to RefreshSessions

Revision ID: cd63b80a8e18
Revises: 77dfe29ef18d
Create Date: 2023-07-21 04:28:01.411121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd63b80a8e18'
down_revision = '77dfe29ef18d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refresh_sessions_user_id_refresh_token_expire_key', 'refresh_sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('refresh_sessions_user_id_refresh_token_expire_key', 'refresh_sessions', ['user_id', 'refresh_token', 'expire'])
    # ### end Alembic commands ###
