"""renamed HotelsUsers users_id to user_id

Revision ID: 972a82b5dbba
Revises: 5dde168e56fd
Create Date: 2023-07-19 15:59:54.936331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972a82b5dbba'
down_revision = '5dde168e56fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels_users_favorite', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('hotels_users_favorite_users_id_fkey', 'hotels_users_favorite', type_='foreignkey')
    op.create_foreign_key(None, 'hotels_users_favorite', 'users', ['user_id'], ['id'])
    op.drop_column('hotels_users_favorite', 'users_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels_users_favorite', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hotels_users_favorite', type_='foreignkey')
    op.create_foreign_key('hotels_users_favorite_users_id_fkey', 'hotels_users_favorite', 'users', ['users_id'], ['id'])
    op.drop_column('hotels_users_favorite', 'user_id')
    # ### end Alembic commands ###
