"""added first_name second_name phone email fields to Booking 

Revision ID: ebb511d6a191
Revises: afd69b376c5f
Create Date: 2023-07-27 14:59:19.009706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb511d6a191'
down_revision = 'afd69b376c5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('second_name', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('phone', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'email')
    op.drop_column('bookings', 'phone')
    op.drop_column('bookings', 'second_name')
    op.drop_column('bookings', 'first_name')
    # ### end Alembic commands ###
