"""added city, address to Hotels

Revision ID: b032b154e6d1
Revises: 7a22e2ede925
Create Date: 2023-07-17 01:17:12.597746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b032b154e6d1'
down_revision = '7a22e2ede925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('city', sa.String(), nullable=True))
    op.add_column('hotels', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'address')
    op.drop_column('hotels', 'city')
    # ### end Alembic commands ###
