"""added stars, description columns and constraints

Revision ID: 7a22e2ede925
Revises: 07127758a87c
Create Date: 2023-07-16 23:43:59.949370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a22e2ede925'
down_revision = '07127758a87c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('stars', sa.Integer(), nullable=True))
    op.add_column('hotels', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'description')
    op.drop_column('hotels', 'stars')
    # ### end Alembic commands ###
