"""added another unique constraint to RefreshSessions again

Revision ID: 77dfe29ef18d
Revises: afd3bd508d4c
Create Date: 2023-07-21 04:18:20.029903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77dfe29ef18d'
down_revision = 'afd3bd508d4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refresh_sessions_user_id_refresh_token_key', 'refresh_sessions', type_='unique')
    op.create_unique_constraint(None, 'refresh_sessions', ['user_id', 'refresh_token', 'expire'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_sessions', type_='unique')
    op.create_unique_constraint('refresh_sessions_user_id_refresh_token_key', 'refresh_sessions', ['user_id', 'refresh_token'])
    # ### end Alembic commands ###
