"""added another unique constraint to RefreshSessions

Revision ID: afd3bd508d4c
Revises: 747917d67993
Create Date: 2023-07-21 04:16:15.738298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd3bd508d4c'
down_revision = '747917d67993'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'refresh_sessions', ['user_id', 'refresh_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_sessions', type_='unique')
    # ### end Alembic commands ###
