"""added unique constraint to HotelsUsers

Revision ID: 52a6bb7d1958
Revises: 972a82b5dbba
Create Date: 2023-07-19 16:12:39.283588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a6bb7d1958'
down_revision = '972a82b5dbba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'hotels_users_favorite', ['hotel_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotels_users_favorite', type_='unique')
    # ### end Alembic commands ###
