"""Added phone field to Bookings as String

Revision ID: ba4c6022ec26
Revises: 1e1049f9a784
Create Date: 2023-07-29 05:47:50.099748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4c6022ec26'
down_revision = '1e1049f9a784'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('phone', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'phone')
    # ### end Alembic commands ###
