"""added nullable args to Hotels

Revision ID: 5cd5dce283b3
Revises: b032b154e6d1
Create Date: 2023-07-17 01:46:43.245824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd5dce283b3'
down_revision = 'b032b154e6d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotels', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hotels', 'stars',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hotels', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hotels', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hotels', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotels', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hotels', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hotels', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hotels', 'stars',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hotels', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
