"""added CheckConstraint to Hotels

Revision ID: 6467a213f4db
Revises: 0f105a40349a
Create Date: 2023-07-23 04:08:31.069715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6467a213f4db"
down_revision = "0f105a40349a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.CheckConstraint("stars >= 1", name="check_min_stars"),
    sa.CheckConstraint("stars <= 5", name="check_max_stars"),
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_min_stars", "hotels", type_="check")
    op.drop_constraint("check_max_stars", "hotels", type_="check")
    # ### end Alembic commands ###
