"""Deleted phone field from Bookings

Revision ID: 1e1049f9a784
Revises: e77185e1521e
Create Date: 2023-07-29 05:46:24.842600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1049f9a784'
down_revision = 'e77185e1521e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
