"""rename image_id to image_url chanedtype from Integer to Varchar

Revision ID: 07127758a87c
Revises: 19d9f6e9726e
Create Date: 2023-07-16 21:13:01.584566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07127758a87c'
down_revision = '19d9f6e9726e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('hotels', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('hotels', 'image_url')
    # ### end Alembic commands ###
